Add modem wakeup support

diff --git a/overlay/system/usr/bin/enable-modem b/overlay/system/usr/bin/enable-modem
--- a/overlay/system/usr/bin/enable-modem
+++ b/overlay/system/usr/bin/enable-modem
@@ -11,9 +11,15 @@ sleep 2
 
 # Set modem audio configs
 if echo "AT+QDAI=1,0,0,2,0,1,1,1" | atinout - /dev/EG25.AT - | grep -q OK; then
-	echo "Successfully configured modem audio"
+        echo "Successfully configured modem audio"
 else
-	echo "Failed to set modem audio up: $?"
+        echo "Failed to set modem audio up: $?"
+fi
+
+if echo 'AT+QCFG="risignaltype","physical"' | atinout - /dev/EG25.AT - | grep -q OK; then
+        echo "Successfully configured modem ring wakeup"
+else
+        echo "Failed to set modem ring wakeup: $?"
 fi
 
 # Wait until the modem is enabled
